console.log(document.querySelector(".box").innerHTML);
console.log(document.querySelector(".container").innerHTML);
console.log(document.querySelector(".box").innerText);
console.log(document.querySelector(".container").innerText);
console.log(document.querySelector(".box").outerHTML);
console.log(document.querySelector(".container").outerHTML);
console.log(document.querySelector(".box").textContent);
console.log(document.querySelector(".container").textContent);
console.log(document.querySelector(".box").hidden = true);
console.log(document.querySelector(".container").hidden);
console.log(document.querySelector(".box").innerHTML="hay this is changed HTML");
console.log(document.querySelector(".container").hasAttribute("style"));
console.log(document.querySelector(".box").hasAttribute("style"));
console.log(document.querySelector(".container").getAttribute("style"));
console.log(document.querySelector(".box").getAttribute("style"));
console.log(document.querySelector(".container").setAttribute("style","display: inline"));
console.log(document.querySelector(".box").setAttribute("style","display: inline"));
console.log(document.querySelector(".container").removeAttribute("style"));
console.log(document.querySelector(".box").Attributes);
console.log(document.querySelector(".container").Attributes);
console.log(document.querySelector(".container").dataset)